[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants]
inherits = "ss12"

[buildPlans.iosevka-custom.variants.design]
capital-q = "crossing"
g = "earless-corner"
m = "earless-rounded-double-arch"
zero = "slashed"
four = "semi-open-non-crossing"
seven = "straight-crossbar"
tilde = "low"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "curly-flat-boundary"
ampersand = "lower-open"
at = "short"
dollar = "open-cap"
percent = "rings-continuous-slash"
question = "corner"

[buildPlans.iosevka-custom.variants.italic]
k = "cursive-serifless"
a = "double-storey-toothless-rounded"

[buildPlans.iosevka-custom.ligations]
inherits = "dlig"

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
